# Generated by Django 5.2.7 on 2025-11-02 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_personalinfo_phone_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personalinfo',
            name='phone',
        ),
        migrations.AddField(
            model_name='personalinfo',
            name='project_link',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
    ]
